"""Build the publication-format Pump It Up model-development report.

The document is organised as a scholarly technical paper rather than as a
teaching-workflow narrative. Quantitative claims are sourced from versioned
repository evidence; visual plates are regenerated by ``academic_figures``.
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from typing import Iterable, Sequence

from docx import Document
from docx.enum.section import WD_ORIENT, WD_SECTION
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_ROW_HEIGHT_RULE, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Mm, Pt, RGBColor

from academic_figures import generate_all


HERE = Path(__file__).resolve().parent
STAGE_ROOT = HERE.parents[1]
DATA_DIR = STAGE_ROOT / "data"
SOURCE_ASSETS = HERE / "assets"
DEFAULT_OUTPUT = HERE / "pump-it-up-model-development-report.docx"
BUILD_DIR = HERE / ".codex-redesign"
FIGURE_DIR = BUILD_DIR / "figures"
LEADERBOARD_SCREENSHOT = SOURCE_ASSETS / "leaderboard-rank-2.png"

NAVY, TEAL, GOLD = "173B57", "2B7A78", "B58528"
BURGUNDY, INK, MUTED = "8B3A4A", "17242D", "59666F"
GRID, PALE, PALE_BLUE, WHITE = "D8DEE3", "F3F6F7", "EAF1F5", "FFFFFF"
BODY_FONT = "Cambria"
PAGE_WIDTH, MARGIN = 11906, 1080
TEXT_WIDTH = PAGE_WIDTH - 2 * MARGIN
COLUMN_WIDTH = (TEXT_WIDTH - 360) // 2


def set_cell_shading(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    node = tc_pr.find(qn("w:shd"))
    if node is None:
        node = OxmlElement("w:shd")
        tc_pr.append(node)
    node.set(qn("w:fill"), fill)


def set_cell_border(cell, **edges: dict[str, str]) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    borders = tc_pr.first_child_found_in("w:tcBorders")
    if borders is None:
        borders = OxmlElement("w:tcBorders")
        tc_pr.append(borders)
    for edge_name, settings in edges.items():
        edge = borders.find(qn(f"w:{edge_name}"))
        if edge is None:
            edge = OxmlElement(f"w:{edge_name}")
            borders.append(edge)
        for key, value in settings.items():
            edge.set(qn(f"w:{key}"), str(value))


def set_cell_margins(cell, top: int = 70, start: int = 90, bottom: int = 70, end: int = 90) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    margins = tc_pr.first_child_found_in("w:tcMar")
    if margins is None:
        margins = OxmlElement("w:tcMar")
        tc_pr.append(margins)
    for side, value in (("top", top), ("start", start), ("bottom", bottom), ("end", end)):
        node = margins.find(qn(f"w:{side}"))
        if node is None:
            node = OxmlElement(f"w:{side}")
            margins.append(node)
        node.set(qn("w:w"), str(value))
        node.set(qn("w:type"), "dxa")


def set_repeat_table_header(row) -> None:
    tr_pr = row._tr.get_or_add_trPr()
    node = OxmlElement("w:tblHeader")
    node.set(qn("w:val"), "true")
    tr_pr.append(node)


def set_table_fixed_widths(table, widths: Sequence[int]) -> None:
    table.autofit = False
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    tbl_pr = table._tbl.tblPr
    tbl_ind = tbl_pr.first_child_found_in("w:tblInd")
    if tbl_ind is None:
        tbl_ind = OxmlElement("w:tblInd")
        tbl_pr.append(tbl_ind)
    tbl_ind.set(qn("w:w"), "0")
    tbl_ind.set(qn("w:type"), "dxa")
    layout = tbl_pr.first_child_found_in("w:tblLayout")
    if layout is None:
        layout = OxmlElement("w:tblLayout")
        tbl_pr.append(layout)
    layout.set(qn("w:type"), "fixed")
    tbl_w = tbl_pr.first_child_found_in("w:tblW")
    tbl_w.set(qn("w:w"), str(sum(widths)))
    tbl_w.set(qn("w:type"), "dxa")
    grid = table._tbl.tblGrid
    for child in list(grid):
        grid.remove(child)
    for width in widths:
        node = OxmlElement("w:gridCol")
        node.set(qn("w:w"), str(width))
        grid.append(node)
    for row in table.rows:
        for index, cell in enumerate(row.cells):
            tc_w = cell._tc.get_or_add_tcPr().first_child_found_in("w:tcW")
            tc_w.set(qn("w:w"), str(widths[index]))
            tc_w.set(qn("w:type"), "dxa")
            set_cell_margins(cell)


def set_keep_with_next(paragraph) -> None:
    p_pr = paragraph._p.get_or_add_pPr()
    if p_pr.find(qn("w:keepNext")) is None:
        p_pr.append(OxmlElement("w:keepNext"))


def set_keep_together(paragraph) -> None:
    p_pr = paragraph._p.get_or_add_pPr()
    if p_pr.find(qn("w:keepLines")) is None:
        p_pr.append(OxmlElement("w:keepLines"))
    if p_pr.find(qn("w:widowControl")) is None:
        p_pr.append(OxmlElement("w:widowControl"))


def style_boxed_paragraph(paragraph, fill: str, accent: str) -> None:
    p_pr = paragraph._p.get_or_add_pPr()
    shading = OxmlElement("w:shd")
    shading.set(qn("w:fill"), fill)
    p_pr.append(shading)
    borders = OxmlElement("w:pBdr")
    for side, size, colour in (("top", "9", accent), ("bottom", "3", GRID)):
        node = OxmlElement(f"w:{side}")
        for key, value in (("val", "single"), ("sz", size), ("space", "4"), ("color", colour)):
            node.set(qn(f"w:{key}"), value)
        borders.append(node)
    p_pr.append(borders)


def set_section_columns(section, count: int, space: int = 360) -> None:
    cols = section._sectPr.find(qn("w:cols"))
    if cols is None:
        cols = OxmlElement("w:cols")
        section._sectPr.append(cols)
    cols.set(qn("w:num"), str(count))
    cols.set(qn("w:space"), str(space))
    cols.set(qn("w:equalWidth"), "1")


def add_page_field(paragraph) -> None:
    run = paragraph.add_run()
    set_run_font(run, BODY_FONT, 6.0, MUTED, False)
    nodes = []
    for kind in ("begin", "separate", "end"):
        node = OxmlElement("w:fldChar")
        node.set(qn("w:fldCharType"), kind)
        nodes.append(node)
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = " PAGE "
    text = OxmlElement("w:t")
    text.text = "1"
    for node in (nodes[0], instr, nodes[1], text, nodes[2]):
        run._r.append(node)


def add_hyperlink(paragraph, text: str, url: str) -> None:
    rel_id = paragraph.part.relate_to(url, "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink", is_external=True)
    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), rel_id)
    run = OxmlElement("w:r")
    run_pr = OxmlElement("w:rPr")
    fonts = OxmlElement("w:rFonts")
    for key in ("ascii", "hAnsi", "eastAsia", "cs"):
        fonts.set(qn(f"w:{key}"), BODY_FONT)
    colour = OxmlElement("w:color")
    colour.set(qn("w:val"), NAVY)
    underline = OxmlElement("w:u")
    underline.set(qn("w:val"), "single")
    run_pr.extend((fonts, colour, underline))
    text_node = OxmlElement("w:t")
    text_node.text = text
    run.extend((run_pr, text_node))
    hyperlink.append(run)
    paragraph._p.append(hyperlink)


def add_alt_text(shape, title: str, description: str) -> None:
    node = shape._inline.docPr
    node.set("name", title)
    node.set("title", title)
    node.set("descr", description)


def set_run_font(run, name: str, size: float | None = None, colour: str | None = None, bold: bool | None = None, italic: bool | None = None) -> None:
    run.font.name = name
    fonts = run._element.get_or_add_rPr().rFonts
    for key in ("ascii", "hAnsi", "eastAsia", "cs"):
        fonts.set(qn(f"w:{key}"), name)
    if size is not None:
        run.font.size = Pt(size)
    if colour is not None:
        run.font.color.rgb = RGBColor.from_string(colour)
    if bold is not None:
        run.bold = bold
    if italic is not None:
        run.italic = italic


def configure_header_footer(section) -> None:
    paragraph = section.header.paragraphs[0]
    paragraph.clear()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.space_after = Pt(0)
    run = paragraph.add_run("EVIDENCE-CONSTRAINED ENSEMBLE LEARNING  •  TECHNICAL REPORT")
    set_run_font(run, BODY_FONT, 6.2, MUTED, True)
    p_pr = paragraph._p.get_or_add_pPr()
    borders = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    for key, value in (("val", "single"), ("sz", "4"), ("space", "4"), ("color", GRID)):
        bottom.set(qn(f"w:{key}"), value)
    borders.append(bottom)
    p_pr.append(borders)
    paragraph = section.footer.paragraphs[0]
    paragraph.clear()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run("ANTHONY P. WATTS  •  ")
    set_run_font(run, BODY_FONT, 6.0, MUTED, False)
    add_page_field(paragraph)


def configure_document(document: Document) -> None:
    section = document.sections[0]
    section.page_width, section.page_height = Mm(210), Mm(297)
    section.orientation = WD_ORIENT.PORTRAIT
    section.top_margin, section.bottom_margin = Inches(0.70), Inches(0.65)
    section.left_margin = section.right_margin = Inches(0.75)
    section.header_distance = section.footer_distance = Inches(0.30)
    set_section_columns(section, 1)
    configure_header_footer(section)

    styles = document.styles
    normal = styles["Normal"]
    normal.font.name = BODY_FONT
    for key in ("ascii", "hAnsi", "eastAsia", "cs"):
        normal._element.rPr.rFonts.set(qn(f"w:{key}"), BODY_FONT)
    language = OxmlElement("w:lang")
    language.set(qn("w:val"), "en-GB")
    language.set(qn("w:eastAsia"), "en-GB")
    normal._element.rPr.append(language)
    normal.font.size = Pt(9.15)
    normal.font.color.rgb = RGBColor.from_string(INK)
    normal.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    normal.paragraph_format.line_spacing = 1.04
    normal.paragraph_format.space_after = Pt(3.2)
    normal.paragraph_format.widow_control = True
    specs = {
        "Title": (BODY_FONT, 18.5, NAVY, True, False, WD_ALIGN_PARAGRAPH.CENTER, 0, 7),
        "Subtitle": (BODY_FONT, 10.1, MUTED, False, True, WD_ALIGN_PARAGRAPH.CENTER, 0, 5),
        "Heading 1": (BODY_FONT, 12.0, NAVY, True, False, WD_ALIGN_PARAGRAPH.LEFT, 10, 3),
        "Heading 2": (BODY_FONT, 10.0, INK, True, False, WD_ALIGN_PARAGRAPH.LEFT, 7, 2),
        "Heading 3": (BODY_FONT, 9.3, NAVY, True, True, WD_ALIGN_PARAGRAPH.LEFT, 5, 1),
        "Caption": (BODY_FONT, 7.5, MUTED, False, False, WD_ALIGN_PARAGRAPH.LEFT, 2, 6),
        "Quote": (BODY_FONT, 8.7, NAVY, False, True, WD_ALIGN_PARAGRAPH.LEFT, 4, 4),
    }
    for name, (font, size, colour, bold, italic, align, before, after) in specs.items():
        style = styles[name]
        style.font.name = font
        for key in ("ascii", "hAnsi", "eastAsia", "cs"):
            style._element.rPr.rFonts.set(qn(f"w:{key}"), font)
        style.font.size = Pt(size)
        style.font.color.rgb = RGBColor.from_string(colour)
        style.font.bold, style.font.italic = bold, italic
        style.paragraph_format.alignment = align
        style.paragraph_format.space_before, style.paragraph_format.space_after = Pt(before), Pt(after)
        style.paragraph_format.keep_with_next = name.startswith("Heading")
    for name in ("List Bullet", "List Number"):
        style = styles[name]
        style.font.name = BODY_FONT
        for key in ("ascii", "hAnsi", "eastAsia", "cs"):
            style._element.rPr.rFonts.set(qn(f"w:{key}"), BODY_FONT)
        style.font.size = Pt(8.9)
        style.paragraph_format.left_indent = Inches(0.16)
        style.paragraph_format.first_line_indent = Inches(-0.12)
        style.paragraph_format.space_after = Pt(1.8)
    for node in styles.element.xpath(".//w:lang"):
        node.set(qn("w:val"), "en-GB")
        node.set(qn("w:eastAsia"), "en-GB")


def start_section(document: Document, columns: int = 1, *, new_page: bool = True) -> None:
    section = document.add_section(WD_SECTION.NEW_PAGE if new_page else WD_SECTION.CONTINUOUS)
    section.page_width, section.page_height = Mm(210), Mm(297)
    section.top_margin, section.bottom_margin = Inches(0.70), Inches(0.65)
    section.left_margin = section.right_margin = Inches(0.75)
    section.header_distance = section.footer_distance = Inches(0.30)
    set_section_columns(section, columns)


def add_body(document: Document, text: str, *, lead: str | None = None) -> None:
    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    if lead and text.startswith(lead):
        run = paragraph.add_run(lead)
        set_run_font(run, BODY_FONT, 9.15, INK, True)
        paragraph.add_run(text[len(lead):])
    else:
        paragraph.add_run(text)
    set_keep_together(paragraph)


def add_bullet(document: Document, text: str) -> None:
    paragraph = document.add_paragraph(style="List Bullet")
    paragraph.add_run(text)
    set_keep_together(paragraph)


def add_heading(document: Document, text: str, level: int = 1) -> None:
    paragraph = document.add_heading(text, level=level)
    set_keep_with_next(paragraph)


def add_column_break(document: Document) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_after = Pt(0)
    paragraph.add_run().add_break(WD_BREAK.COLUMN)


def add_figure(document: Document, path: Path, number: int, title: str, caption: str, alt: str, width: float = 6.70) -> None:
    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.space_before = Pt(1)
    paragraph.paragraph_format.space_after = Pt(0)
    shape = paragraph.add_run().add_picture(str(path), width=Inches(width))
    add_alt_text(shape, f"Figure {number}. {title}", alt)
    set_keep_with_next(paragraph)
    cap = document.add_paragraph(style="Caption")
    run = cap.add_run(f"Figure {number} | {title}. ")
    set_run_font(run, BODY_FONT, 7.5, NAVY, True)
    cap.add_run(caption)
    set_keep_together(cap)


def add_table(document: Document, headers: Sequence[str], rows: Iterable[Sequence[str]], widths: Sequence[int], caption: tuple[int, str] | None = None) -> None:
    if caption:
        number, title = caption
        cap = document.add_paragraph(style="Caption")
        run = cap.add_run(f"Table {number} | {title}")
        set_run_font(run, BODY_FONT, 7.5, NAVY, True)
        cap.paragraph_format.space_after = Pt(2)
        set_keep_with_next(cap)
    table = document.add_table(rows=1, cols=len(headers))
    centred_headers = {"Rows", "Wt.", "Fit + predict", "Dev.", "Local test", "Public"}
    header = table.rows[0]
    set_repeat_table_header(header)
    for index, text in enumerate(headers):
        cell = header.cells[index]
        cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
        set_cell_shading(cell, NAVY)
        paragraph = cell.paragraphs[0]
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER if text in centred_headers else WD_ALIGN_PARAGRAPH.LEFT
        run = paragraph.add_run(text)
        set_run_font(run, BODY_FONT, 7.1, WHITE, True)
    for row_index, values in enumerate(rows):
        row = table.add_row()
        row.height_rule = WD_ROW_HEIGHT_RULE.AT_LEAST
        for index, value in enumerate(values):
            cell = row.cells[index]
            cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
            set_cell_shading(cell, WHITE if row_index % 2 == 0 else PALE)
            paragraph = cell.paragraphs[0]
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER if headers[index] in centred_headers else WD_ALIGN_PARAGRAPH.LEFT
            paragraph.paragraph_format.space_after = Pt(0)
            run = paragraph.add_run(str(value))
            set_run_font(run, BODY_FONT, 7.0, INK, index == 0)
            set_cell_border(cell, bottom={"val": "single", "sz": "3", "color": GRID})
    set_table_fixed_widths(table, widths)
    document.add_paragraph().paragraph_format.space_after = Pt(0)


def add_callout(document: Document, label: str, statement: str, colour: str = TEAL) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_before = Pt(3)
    paragraph.paragraph_format.space_after = Pt(5)
    paragraph.paragraph_format.left_indent = Pt(4)
    paragraph.paragraph_format.right_indent = Pt(4)
    style_boxed_paragraph(paragraph, PALE, colour)
    run = paragraph.add_run(f"{label.upper()}  |  ")
    set_run_font(run, BODY_FONT, 7.2, colour, True)
    run = paragraph.add_run(statement)
    set_run_font(run, BODY_FONT, 8.6, INK, False)
    set_keep_together(paragraph)


def add_title_page(document: Document, figures: dict[str, Path]) -> None:
    title = document.add_paragraph(style="Title")
    title.paragraph_format.space_before = Pt(15)
    title.add_run("Evidence-Constrained Ensemble Learning for\nMulticlass Waterpoint Condition Assessment")
    subtitle = document.add_paragraph(style="Subtitle")
    subtitle.add_run("A reproducible study of the DrivenData Pump It Up challenge")
    author = document.add_paragraph()
    author.alignment = WD_ALIGN_PARAGRAPH.CENTER
    author.paragraph_format.space_after = Pt(1)
    run = author.add_run("Anthony P. Watts")
    set_run_font(run, BODY_FONT, 10.3, INK, True)
    meta = document.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.paragraph_format.space_after = Pt(8)
    run = meta.add_run("Revised 28 August 2026  |  Public result observed 23 August 2026")
    set_run_font(run, BODY_FONT, 6.8, MUTED, False)

    abstract = (
        "Background: Multiclass waterpoint assessment combines a majority functional class, a small repair class, and marked spatial heterogeneity. "
        "Objective: This study evaluated whether a leakage-controlled ensemble could improve classification accuracy while preserving a reproducible link between the input data, model selection, and public evaluation. "
        "Methods: The analysis used 59,400 labelled Tanzanian waterpoints and 14,850 unlabelled competition records. A fixed stratified development/local-test design, five-fold cross-validation, and cross-fitted supervised transforms separated model selection from final assessment. Candidate families comprised linear, tree, nearest-neighbour, boosting, and bagging methods. Candidate changes entered the final soft-voting ensemble only when they met prespecified promotion criteria. "
        "Results: The six-component ensemble achieved 81.8981% development accuracy, 81.3973% on the fixed local test set, and 0.8298 on the public leaderboard. The public result exceeded the prespecified 0.826 target by 0.0038 and ranked second in the observed snapshot. The final two local increments were +0.1684 percentage points (exact McNemar p=0.135) and +0.0421 points (p=0.542), with both confidence intervals including zero. "
        "Conclusion: Representation-specific models and controlled high-cardinality features accounted for most of the improvement. The public score is benchmark evidence; it does not establish operational or causal validity. Regional transport, temporal drift, and repair-class performance require separate evaluation."
    )
    p = document.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    p.paragraph_format.line_spacing = 1.0
    p.paragraph_format.space_after = Pt(4)
    p.paragraph_format.left_indent = p.paragraph_format.right_indent = Pt(5)
    style_boxed_paragraph(p, PALE_BLUE, TEAL)
    run = p.add_run("ABSTRACT\n")
    set_run_font(run, BODY_FONT, 7.0, NAVY, True)
    run = p.add_run(abstract)
    set_run_font(run, BODY_FONT, 8.1, INK, False)
    set_keep_together(p)
    keywords = document.add_paragraph()
    keywords.paragraph_format.space_before = Pt(5)
    keywords.paragraph_format.space_after = Pt(5)
    run = keywords.add_run("Keywords: ")
    set_run_font(run, BODY_FONT, 7.8, NAVY, True)
    run = keywords.add_run("multiclass classification; ensemble learning; leakage control; spatial heterogeneity; class imbalance; reproducible machine learning")
    set_run_font(run, BODY_FONT, 7.8, MUTED, False)
    add_figure(
        document, figures["study_design"], 1, "Study design and evidential separation",
        "The analysis preserves three distinct evidential roles: cross-validation supports candidate comparison; the fixed local test set supports paired final assessment; and the competition labels remain unavailable. Arrows denote information flow, not chronology.",
        "A study-design diagram showing 59,400 labelled records split into development and local-test sets, five-fold cross-validation within development data, and a final submission of 14,850 unlabelled competition records.",
        width=6.55,
    )


def add_introduction(document: Document) -> None:
    add_heading(document, "1  Introduction", 1)
    add_body(document, "Reliable infrastructure assessment is a classification problem with a consequential error structure. A waterpoint recorded as functional, functional but requiring repair, or non-functional may influence inspection priorities and maintenance planning, yet the three labels are not equally common, separable, or costly to confuse. The Pump It Up benchmark provides a compact setting in which to examine predictive performance, validation design, and the limits of the resulting claims.", lead="Reliable infrastructure assessment")
    add_body(document, "The task contains several recognised sources of machine-learning error: high-cardinality names, partially missing administrative fields, implausible zero values, duplicated semantic encodings, strong geographical structure, and a repair class comprising only 7.27% of labelled observations. Flexible learners can use these signals, but they can also amplify leakage, memorise unstable identities, or produce optimistic estimates after repeated use of the same validation data. The analysis therefore reports model performance, allocation of evidence, rejected candidates, and uncertainty around small improvements.")
    add_body(document, "The study addresses three questions: which model families perform credibly before extensive tuning; whether representation diversity and controlled high-cardinality information improve a strong tree ensemble; and whether development, local-test, and public evidence support the same model ordering. Preprocessing is fitted within folds, candidate changes are assessed against a prespecified promotion rule, and public results are reported alongside local evidence.")
    add_callout(document, "Study scope", "Leakage-controlled validation; a complete candidate ledger; a six-model probability ensemble; paired uncertainty for the final local increments; and a reproducible submission artefact with a cryptographic checksum.")

    add_heading(document, "2  Data and problem formulation", 1)
    add_heading(document, "2.1  Source, unit of analysis and outcome", 2)
    add_body(document, "The data originate from the DrivenData Pump It Up: Data Mining the Water Table competition [1]. Each row represents one Tanzanian waterpoint described by geographical, administrative, management, extraction, payment, quantity, quality, and construction attributes. The labelled set contains 59,400 observations, and the competition set contains 14,850 observations. The response is nominal, with three mutually exclusive classes: functional, functional needs repair, and non-functional.")
    add_body(document, "The primary estimand is predictive: the probability distribution over the three recorded status classes for a previously unseen row drawn under the benchmark’s sampling process. It is not a causal estimand. The analysis does not claim that changing a feature such as management type or payment policy would cause a change in waterpoint condition.")
    add_column_break(document)
    add_table(
        document, ["Partition", "Rows", "Analytical role"],
        [
            ("Development", "47,520", "Fitting, cross-validation, and model selection"),
            ("Local test", "11,880", "Paired final assessment"),
            ("Competition", "14,850", "Frozen submission and public evaluation"),
        ], [1150, 650, 2893], caption=(1, "Partition roles and access constraints"),
    )
    add_heading(document, "2.2  Outcome imbalance and data quality", 2)
    add_body(document, "The training distribution is dominated by functional waterpoints (32,259; 54.31%), followed by non-functional points (22,824; 38.42%), and the minority repair class (4,317; 7.27%). Accuracy is therefore interpretable only against a 54.31% majority baseline and should be accompanied by class-sensitive diagnostics. The repair class is especially important: a superficially strong model may gain overall accuracy while eroding recall for precisely the observations that signal emerging failure.")
    add_body(document, "Missingness and placeholder values are not interchangeable. Scheme name is missing for 48.50% of labelled rows, whereas several numeric fields use zero at implausibly high rates: 70.10% for amount_tsh, 35.99% for population, 34.86% for construction_year, and 34.41% for gps_height. High cardinality is similarly concentrated: wpt_name has 37,400 observed levels, subvillage has 19,288, and scheme_name has 2,696. These properties motivated explicit missing indicators, robust transformations, and separate treatment of identity-like variables.")
    add_body(document, "Coordinates require additional care. Of the 59,400 labelled rows, 57,588 contain valid mapped locations; 1,812 were excluded from spatial summaries because longitude and latitude values were invalid or missing. This exclusion affects the diagnostic maps, not the primary labelled sample.")


def add_data_plates(document: Document, figures: dict[str, Path]) -> None:
    start_section(document, 1)
    add_figure(document, figures["data_anatomy"], 2, "Data anatomy: imbalance, missingness and cardinality",
        "Class composition is shown with exact labelled counts. Missingness and zero-rate panels distinguish absent categorical values from structurally suspicious numeric zeros. Cardinality is plotted for fields whose naïve one-hot treatment would produce a large, sparse representation. Percentages are calculated directly from the versioned training files.",
        "A four-panel plate displaying class counts and percentages, the leading missing-value rates, numeric zero rates, and high-cardinality categorical fields in the labelled dataset.")
    add_figure(document, figures["spatial"], 3, "Spatial heterogeneity in observed waterpoint condition",
        "Point locations are mapped for the 57,588 labelled rows with valid coordinates. Regional summaries show that the class balance is geographically structured, motivating both spatial features and caution about transport to new regions. The map is descriptive and does not establish spatial causation.",
        "A map of Tanzanian waterpoint observations coloured by status, with regional summaries of functional, repair, and non-functional shares.")


def add_methods(document: Document) -> None:
    start_section(document, 2)
    add_heading(document, "3  Methods", 1)
    add_heading(document, "3.1  Auditable preprocessing", 2)
    add_body(document, "Preprocessing was implemented as part of each fitted pipeline so that no statistic learned from held-back outcomes entered a training fold. The raw identifier was reserved for submission joining and excluded as a direct predictor. Variables were reviewed for semantic duplication, prediction-time availability, and encoding feasibility; categorical levels were normalised without imposing an ordinal interpretation.")
    add_body(document, "Numeric handling distinguished measurement from absence. Log-like compression was applied where heavy right tails made raw scale uninformative; missing or placeholder states were retained through indicators rather than silently converted to typical values. Construction year was represented both as a reported value and as an availability signal because zero commonly denoted unknown vintage. Coordinate validity was checked before spatial derivations.")
    add_body(document, "Categorical handling followed the representation and learner. Low- and moderate-cardinality variables were one-hot encoded for linear and distance-based baselines. Tree ensembles used compact ordinal or frequency encodings. CatBoost received native categorical identities, with its ordered statistics providing a leakage-resistant mechanism for high-cardinality categories [5]. Any outcome-informed encoding was cross-fitted: the mapping for a row was estimated without its own target or targets from its held-out fold.")

    add_heading(document, "3.2  Validation and promotion rules", 2)
    add_body(document, "A single stratified split allocated 47,520 rows to development and 11,880 to a fixed local test set. All search decisions were made within the development partition, primarily through five fixed stratified folds. The local set was reserved for later paired comparisons, and the competition set remained label-blind. Random seeds and row allocation were fixed before the deep search phase.")
    add_body(document, "A candidate was promoted only if it improved mean cross-validated accuracy by at least 0.10 percentage points, improved at least three of five folds, lost no more than 0.25 points on any fold, and reduced repair recall by no more than 2 points. The gate is a governance rule rather than a significance test: it makes the evidential threshold explicit and limits selection on noise. Small positive results could still be recorded without entering the production ensemble.")
    add_callout(document, "Separation", "Cross-validation selected representations and learners; the fixed local test compared mature candidates; the public leaderboard assessed a frozen submission. The three roles are not interchangeable.", colour=NAVY)

    add_heading(document, "3.3  Candidate model families", 2)
    add_body(document, "The initial comparison spanned a majority classifier, multinomial logistic regression, Gaussian naïve Bayes, a decision tree, k-nearest neighbours, Extra Trees, histogram gradient boosting, and Random Forest. The comparison tested linearity, local geometry, conditional-independence assumptions, single-tree variance, and the effects of bagging and boosting. Random Forests average decorrelated trees [2]; gradient boosting adds weak learners stage-wise to optimise a differentiable loss [3]; XGBoost supplies regularised, scalable tree boosting [4].")
    add_body(document, "The final synthesis used probability averaging rather than hard majority voting. For class c and observation x, the combined probability was")
    equation = document.add_paragraph()
    equation.alignment = WD_ALIGN_PARAGRAPH.CENTER
    equation.paragraph_format.space_before = equation.paragraph_format.space_after = Pt(4)
    run = equation.add_run("p̂(c | x) = Σₘ wₘ p̂ₘ(c | x),     ŷ = arg maxᶜ p̂(c | x),     Σₘ wₘ = 1.")
    set_run_font(run, BODY_FONT, 10.2, INK, False, True)
    add_body(document, "Weights were constrained to be non-negative and chosen through bounded comparisons rather than unconstrained continuous optimisation. This preserved interpretability and reduced the effective search surface. Ensemble methods can reduce error when component models make partially uncorrelated mistakes, but diversity is useful only when each component adds signal [6].")

    add_heading(document, "3.4  Metrics and paired uncertainty", 2)
    add_body(document, "Overall accuracy was the competition-aligned primary metric. Macro recall and class-specific recall were retained as safeguards against majority-class dominance; multiclass log loss and Brier score assessed probability quality where available [9]. For two mature candidates evaluated on the same local rows, the analysis used the discordant-pair formulation of McNemar’s exact test [8]. A paired bootstrap interval described the accuracy difference. These procedures quantify uncertainty conditional on the fixed local sample; they do not correct for the upstream reuse of development evidence.")


def add_validation_and_models(document: Document, figures: dict[str, Path]) -> None:
    start_section(document, 1)
    add_figure(document, figures["validation"], 4, "Leakage-aware validation architecture and promotion gate",
        "Only the development partition participates in repeated candidate comparison. Supervised transforms are fitted inside each fold. The local test remains untouched until candidates are mature, while the competition labels are never available. The gate combines a minimum mean effect with fold consistency and repair-class safeguards.",
        "A validation schematic with development, local-test, and competition partitions, five internal folds, cross-fitted transformations, and four explicit promotion thresholds.")
    add_figure(document, figures["model_family"], 5, "Model-family evidence before deep tuning",
        "Bars report mean five-fold accuracy and repair-class recall; point-and-range marks show fold accuracy dispersion. Gaussian naïve Bayes is diagnostically informative rather than competitive: its 94.67% repair recall accompanies only 28.33% overall accuracy. The 50:50 Extra Trees plus histogram gradient-boosting vote reaches 80.83% mean accuracy and establishes the first ensemble reference.",
        "A multi-panel comparison of nine candidate families showing overall accuracy, repair-class recall, and fold-to-fold accuracy variation.")


def add_model_development(document: Document) -> None:
    start_section(document, 2)
    add_heading(document, "4  Bounded model development", 1)
    add_heading(document, "4.1  Representation-specific candidate models", 2)
    add_body(document, "The initial model-family screen showed that flexible tree ensembles substantially outperformed the majority baseline. Repair recall varied much more than overall accuracy, so a single aggregate score did not describe the principal class trade-off. Probability averaging between two structurally different learners produced a modest improvement and supplied the reference for subsequent representation-specific comparisons.")
    add_body(document, "Subsequent work introduced three classes of signal. Identity representations retained names and administrative categories in controlled forms. Spatial representations derived location, elevation, and neighbourhood context while handling invalid coordinates explicitly. Categorical-frequency representations compressed sparse identities into prevalence information suitable for bagged trees. XGBoost, Random Forest, and CatBoost then supplied distinct inductive biases over these views.")
    add_body(document, "Algorithm family and input representation were treated as separate sources of variation. Estimators from different families can remain highly correlated when they use the same features; conversely, models from one family can differ when trained on distinct representations. The final architecture contains two XGBoost components, three Random Forest variants, and one CatBoost model, with no duplicate feature/model configuration.")

    add_heading(document, "4.2  Evaluation of candidate modifications", 2)
    add_body(document, "The search ledger records every evaluated modification. Regional partial pooling, geographic centroids, population median substitution, an MLP voter, and a small neural-network weight did not improve the accepted reference. Against the promoted identity baseline, frequency-only identity, confident-label filtering, name-text features, calendar categories, and pseudo-labelling were neutral or harmful. Additional feature engineering did not provide a consistent gain under the fixed folds.")
    add_body(document, "Complete-identity CatBoost at 20% weight was the only candidate to meet the full promotion rule. Its mean gain was +0.116 percentage points, with improvement in four of five folds. Several smaller positive estimates were recorded but not retained because they failed the prespecified practical threshold.")

    add_heading(document, "4.3  Final ensemble specification", 2)
    add_body(document, "The frozen ensemble used seed 20260824 and six probability-producing components. Weights summed to one: 33% deep top-50 identity XGBoost, 11% spatial XGBoost, 18% accepted Random Forest, 9% categorical-frequency Random Forest, 9% spatial-height Random Forest, and 20% complete-identity CatBoost. Full-data fit-and-predict time totalled approximately 122.3 seconds on the recorded environment, with individual components ranging from 4.864 to 31.714 seconds.")
    add_column_break(document)
    add_table(document, ["Component", "Representation", "Wt.", "Fit + predict"], [
        ("XGBoost: deep identity", "Top-50 identities; depth 17; 600 trees", "33%", "23.266 s"),
        ("XGBoost: spatial", "Spatial representation; 1,082 iterations", "11%", "9.215 s"),
        ("Random Forest: accepted", "Accepted baseline representation", "18%", "31.714 s"),
        ("Random Forest: frequency", "Categorical-frequency representation", "9%", "4.864 s"),
        ("Random Forest: height", "Spatial-height representation", "9%", "31.169 s"),
        ("CatBoost: complete identity", "Native complete-identity categories; 2,173 iterations", "20%", "22.040 s"),
    ], [1270, 2060, 590, 773], caption=(2, "Frozen six-component probability ensemble"))


def add_search_and_ensemble_plates(document: Document, figures: dict[str, Path]) -> None:
    start_section(document, 1)
    add_figure(document, figures["search_ledger"], 6, "Bounded search ledger: accepted, observed and rejected hypotheses",
        "Accuracy deltas are mean five-fold changes in percentage points relative to the named reference. The shaded promotion region begins at +0.10 points. A positive point estimate is not sufficient for promotion: candidates must also satisfy fold-consistency, worst-fold and repair-recall constraints. Recording negative results reduces hindsight bias and prevents repeated exploration of already weak ideas.",
        "A diverging search-ledger chart showing negative and positive cross-validation deltas for fourteen candidate changes and identifying complete-identity CatBoost as the only full-gate promotion.")
    add_figure(document, figures["ensemble"], 7, "Final ensemble architecture",
        "Six calibrated class-probability vectors enter a weighted linear pool. Line thickness and percentages encode component weight. The right-hand nodes show hard-prediction shares in the competition submission, not estimated population prevalence. The repair share of 3.643% is materially lower than its 7.27% frequency in the labelled data and remains an important caution.",
        "A model architecture diagram with six weighted XGBoost, Random Forest, and CatBoost components feeding a soft-voting probability fusion and three output classes.")


def add_results(document: Document) -> None:
    start_section(document, 2)
    add_heading(document, "5  Results", 1)
    add_heading(document, "5.1  Candidate progression", 2)
    add_body(document, "The accepted 55:45 XGBoost-Random Forest vote established 81.6246% development accuracy, 80.6987% local accuracy in its exact later refit, and a public score of 0.8241. Identity-aware modelling increased these values to 81.7403%, 81.0859%, and 0.8259. The archived ensemble reached 81.7929% development accuracy, 81.1869% locally, and 0.8288 publicly. A deeper seed-20260822 synthesis improved local performance to 81.3552% but was not submitted. The final seed-20260824 model reached 81.8981% development accuracy and 81.3973% locally.")
    add_body(document, "The frozen competition submission scored 0.8298. This exceeded the 0.826 target by 0.0038 and occupied rank 2 in the leaderboard snapshot observed on 23 August 2026, 0.0001 behind the displayed leader. The result is strong benchmark evidence, but the leaderboard is an adaptively consulted external validation surface rather than an independent scientific test after multiple submissions.")
    add_table(document, ["Candidate", "Dev.", "Local test", "Public", "Decision"], [
        ("Accepted vote", "81.6246%", "80.6987%", "0.8241", "Reference"),
        ("Identity vote", "81.7403%", "81.0859%", "0.8259", "Promoted"),
        ("Archived synthesis", "81.7929%", "81.1869%", "0.8288", "Superseded"),
        ("Deep seed 20260822", "81.8771%", "81.3552%", "N/A", "Local comparison"),
        ("Final seed 20260824", "81.8981%", "81.3973%", "0.8298", "Frozen"),
    ], [1200, 850, 850, 680, 1113], caption=(3, "Evidence progression for mature candidates"))

    add_heading(document, "5.2  Paired local uncertainty", 2)
    add_body(document, "Relative to the archived synthesis, the deep seed-20260822 model gained 20 net correct rows on the 11,880-row local test set, equivalent to +0.1684 percentage points. The paired 95% interval ranged from -0.0421 to +0.3788 points, and the exact McNemar p-value was 0.135. Replacing seed 20260822 with seed 20260824 gained five net rows (+0.0421 points), with a 95% interval from -0.0673 to +0.1515 and p=0.542.")
    add_body(document, "Neither final increment is conventionally significant. That does not prove equivalence, nor does it invalidate the frozen model; it establishes that the local sample cannot resolve effects this small with confidence. The appropriate interpretation is stability with modest directional improvement, not evidence of a dramatic algorithmic advance.")

    add_heading(document, "5.3  Public prediction composition", 2)
    add_body(document, "The final submission predicted 60.721% of competition rows as functional, 35.636% as non-functional, and 3.643% as functional needs repair. These are model outputs, not ground-truth prevalence estimates. The low repair share is consistent with the class’s weak separability across model families and should be treated as a deployment risk: a high-accuracy decision system could under-route preventative maintenance if hard labels were used without calibrated thresholds or human review.")
    add_callout(document, "Primary result", "81.3973% fixed local-test accuracy and 0.8298 public classification rate. The two measures support the same ordering at the end of development, but they answer different evidential questions.", colour=BURGUNDY)


def add_result_plates(document: Document, figures: dict[str, Path]) -> None:
    start_section(document, 1)
    add_figure(document, figures["convergence"], 8, "Convergence across development, local and public evidence",
        "Panels A-C show candidate progression on the three evidence surfaces. Panel D reports paired local-test accuracy differences with 95% intervals and exact McNemar p-values. The smallest final changes remain statistically unresolved.",
        "A four-panel plate showing five candidate scores on development, local-test, and public evaluations, plus two paired local differences with confidence intervals crossing zero.")
    add_figure(document, figures["leaderboard"], 9, "Public leaderboard evidence snapshot",
        "The captured leaderboard shows the final public score of 0.8298 and observed rank 2 on 23 August 2026. The image is retained as provenance for the external result; it is not a substitute for local evaluation and should not be interpreted as an estimate of future operational performance.",
        "A framed screenshot of the DrivenData Pump It Up public leaderboard with the relevant entry highlighted and an annotation recording score 0.8298, rank 2, and observation date 23 August 2026.", width=6.60)


def add_discussion(document: Document) -> None:
    start_section(document, 2)
    add_heading(document, "6  Discussion", 1)
    add_heading(document, "6.1  What the evidence supports", 2)
    add_body(document, "The heterogeneous, leakage-controlled ensemble outperformed the generic baselines and achieved a competitive public score. Statistical support is stronger for the full development trajectory than for the final few hundredths of a percentage point. Tree ensembles performed consistently; identity and spatial representations added residual information; and the final CatBoost component was the only late candidate to meet the complete promotion rule.")
    add_body(document, "The pattern is consistent with the structure of the problem. High-cardinality local names can encode maintenance history, administrative practice, or geography that coarse categories miss. Native or controlled identity treatment allows these signals to contribute without producing an unmanageably sparse matrix. Spatial representations capture regional heterogeneity, while bagging and boosting smooth different kinds of variance. Probability averaging then benefits from disagreement among reasonably accurate components.")
    add_body(document, "Pseudo-labelling, confident-label filtering, and additional hand-engineered interactions did not produce reliable gains. The remaining error may reflect ambiguous labels, unobserved maintenance history, temporal mismatch, or difficult boundary cases. Independent data collection and error adjudication would test these explanations more directly than further unconstrained comparison of minor variants.")

    add_heading(document, "6.2  Accuracy, probability quality and decision use", 2)
    add_body(document, "Competition accuracy gives every row equal weight and converts a probability vector to one hard label. An operational maintenance system would require a different objective. Missing a repairable waterpoint may be more costly than inspecting an ultimately functional one; capacity constraints may favour ranking rather than three-way classification; and probability calibration may matter more than a small accuracy difference. The benchmark result therefore evaluates model development under competition conditions; it does not specify an intervention policy.")
    add_body(document, "A safer operational interface would expose class probabilities, uncertainty, and selected provenance fields to a reviewer. Thresholds should be chosen against explicit inspection costs and validated prospectively. Monitoring should stratify error and calibration by geography, waterpoint type, and time since construction, with an escalation path for areas poorly represented in the training sample.")

    add_heading(document, "7  Limitations and threats to validity", 1)
    add_heading(document, "7.1  Internal validity", 2)
    add_body(document, "Mature variants were eventually compared on the fixed local test set. Repeated consultation weakens its interpretation as a pristine confirmatory sample, so the analysis reports paired uncertainty and treats this evidence as comparative. Strict confirmation would require a newly locked sample.")
    add_body(document, "Cross-validation remains conditional on the folds, pipeline, and candidate search. Model selection can be optimistic even when each fold is implemented correctly [7]. The promotion gate limits rather than eliminates this bias; fixed seeds support reproducibility, not certainty.")

    add_heading(document, "7.2  External validity", 2)
    add_body(document, "Fifteen submissions created opportunities for adaptive leaderboard feedback, so the final public score is not independent of development decisions. Spatial and temporal transport is also untested: administrative practice, technology, climate, and recording standards can differ by district and time.")
    add_body(document, "Identity features are particularly vulnerable to drift. Frequency and native categorical treatments handle unseen levels mechanically, but cannot supply missing domain signal. Performance must therefore be re-estimated for new regions and periods rather than assumed to transfer.")

    add_heading(document, "7.3  Measurement and responsible use", 2)
    add_body(document, "Recorded status is an administrative label, not a direct measure of water safety or community need. Label noise and inspection timing may blur functional and repair states, while geographical data inequalities can be reproduced. Automated denial or deferral of maintenance would be inappropriate without local validation and accountable human oversight.")

    add_heading(document, "8  Conclusion", 1)
    add_body(document, "This study developed a six-component ensemble for multiclass waterpoint condition assessment using fixed evidence partitions, cross-fitted transforms, a practical promotion gate, and explicit negative-result reporting. The frozen model achieved 81.3973% local-test accuracy and a 0.8298 public score, exceeding the prespecified public target and ranking second in the observed snapshot.")
    add_body(document, "The largest gains followed changes in representation and ensemble composition, whereas the final local increments were small and uncertain. Additional model complexity was not retained when it failed the prespecified rule. Further work should prioritise independent temporal or regional validation, richer maintenance-history data, probability calibration, and decision-specific costs.")


def add_references_and_appendix(document: Document) -> None:
    start_section(document, 2)
    add_heading(document, "References", 1)
    references = [
        ("[1]", "DrivenData. Pump It Up: Data Mining the Water Table. Competition data and evaluation page. Accessed 28 August 2026.", "https://www.drivendata.org/competitions/7/pump-it-up-data-mining-the-water-table/"),
        ("[2]", "Breiman L. Random forests. Machine Learning. 2001;45:5-32. doi:10.1023/A:1010933404324.", "https://doi.org/10.1023/A:1010933404324"),
        ("[3]", "Friedman JH. Greedy function approximation: a gradient boosting machine. Annals of Statistics. 2001;29(5):1189-1232. doi:10.1214/aos/1013203451.", "https://doi.org/10.1214/aos/1013203451"),
        ("[4]", "Chen T, Guestrin C. XGBoost: a scalable tree boosting system. Proceedings of the 22nd ACM SIGKDD. 2016:785-794. doi:10.1145/2939672.2939785.", "https://doi.org/10.1145/2939672.2939785"),
        ("[5]", "Prokhorenkova L, Gusev G, Vorobev A, Dorogush AV, Gulin A. CatBoost: unbiased boosting with categorical features. Advances in Neural Information Processing Systems 31. 2018.", "https://proceedings.neurips.cc/paper/2018/hash/14491b756b3a51daac41c24863285549-Abstract.html"),
        ("[6]", "Dietterich TG. Ensemble methods in machine learning. Multiple Classifier Systems. 2000:1-15. doi:10.1007/3-540-45014-9_1.", "https://doi.org/10.1007/3-540-45014-9_1"),
        ("[7]", "Varma S, Simon R. Bias in error estimation when using cross-validation for model selection. BMC Bioinformatics. 2006;7:91. doi:10.1186/1471-2105-7-91.", "https://doi.org/10.1186/1471-2105-7-91"),
        ("[8]", "McNemar Q. Note on the sampling error of the difference between correlated proportions or percentages. Psychometrika. 1947;12:153-157. doi:10.1007/BF02295996.", "https://doi.org/10.1007/BF02295996"),
        ("[9]", "Brier GW. Verification of forecasts expressed in terms of probability. Monthly Weather Review. 1950;78(1):1-3.", "https://doi.org/10.1175/1520-0493(1950)078%3C0001:VOFEIT%3E2.0.CO;2"),
        ("[10]", "Kohavi R. A study of cross-validation and bootstrap for accuracy estimation and model selection. Proceedings of IJCAI. 1995:1137-1145.", "https://www.ijcai.org/Proceedings/95-2/Papers/016.pdf"),
        ("[11]", "Lemaître G, Nogueira F, Aridas CK. Imbalanced-learn: a Python toolbox to tackle the curse of imbalanced datasets in machine learning. Journal of Machine Learning Research. 2017;18(17):1-5.", "https://jmlr.org/papers/v18/16-365.html"),
    ]
    for label, citation, url in references:
        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
        paragraph.paragraph_format.left_indent = Inches(0.18)
        paragraph.paragraph_format.first_line_indent = Inches(-0.18)
        paragraph.paragraph_format.space_after = Pt(2.5)
        run = paragraph.add_run(f"{label} {citation} ")
        set_run_font(run, BODY_FONT, 7.4, INK, False)
        add_hyperlink(paragraph, "Source", url)
        set_keep_together(paragraph)

    add_heading(document, "Appendix A  Reproducibility record", 1)
    add_heading(document, "A.1  Frozen artefact", 2)
    add_body(document, "The competition submission contained 14,850 rows in the required single-label schema. Its SHA-256 checksum was fe5de9ea46bad2b35226bc97ebdfb743807fb758df1d259e8f8a51609808fee2. The final ensemble seed was 20260824. The public result was captured on 23 August 2026 and the report was revised on 28 August 2026.")
    add_heading(document, "A.2  Evidence register", 2)
    add_table(document, ["Evidence item", "Repository location / purpose"], [
        ("Raw data", "data/TrainingSetValues.csv; TrainingSetLabels.csv; TestSetValues.csv"),
        ("Model-family benchmark", "notebooks/03_model_selection_and_training.ipynb"),
        ("Bounded synthesis", "notebooks/06_deep-model-search-and-submit.ipynb"),
        ("Submission manifest", "reports/deep-search-submission-summary.md"),
        ("Evaluation record", "reports/model-evaluation-and-interpretation.md"),
        ("Method provenance", "reports/model-development-methodology.md"),
        ("Leaderboard evidence", "reports/publication/assets/leaderboard-rank-2.png"),
    ], [1250, 3443], caption=(4, "Primary internal evidence sources"))
    add_heading(document, "A.3  Reproduction boundary", 2)
    add_body(document, "The report generator reconstructs all analytical plates from the versioned CSV files or the numerical evidence recorded in the repository. The leaderboard image is retained as a dated external evidence capture. Exact reproduction of the public score additionally depends on the frozen fitted configuration, package versions, and the competition evaluator; the public labels are not present locally.")
    add_heading(document, "A.4  Reporting checklist", 2)
    for item in [
        "Problem, unit of analysis, classes, and primary metric stated explicitly.",
        "Development, local-test, and competition evidence assigned non-overlapping analytical roles.",
        "Cross-fitted supervised transformations and fixed random seeds documented.",
        "Rejected as well as promoted model changes retained in the search ledger.",
        "Paired effect sizes, intervals, and exact tests reported for final local comparisons.",
        "Public leaderboard adaptivity, data drift, measurement validity, and responsible-use limits disclosed.",
    ]:
        add_bullet(document, item)


def build_report(output_path: Path) -> None:
    if not LEADERBOARD_SCREENSHOT.exists():
        raise FileNotFoundError(f"Missing leaderboard evidence: {LEADERBOARD_SCREENSHOT}")
    figures = generate_all(DATA_DIR, FIGURE_DIR, LEADERBOARD_SCREENSHOT)
    document = Document()
    configure_document(document)
    properties = document.core_properties
    properties.title = "Evidence-Constrained Ensemble Learning for Multiclass Waterpoint Condition Assessment"
    properties.subject = "Reproducible model development for the DrivenData Pump It Up challenge"
    properties.author = "Anthony P. Watts"
    properties.keywords = "machine learning; ensemble learning; waterpoint condition; reproducibility; class imbalance"
    properties.comments = "Publication-format technical report generated from versioned repository evidence."
    properties.last_modified_by = "Anthony P. Watts"
    add_title_page(document, figures)
    start_section(document, 2)
    add_introduction(document)
    add_data_plates(document, figures)
    add_methods(document)
    add_validation_and_models(document, figures)
    add_model_development(document)
    add_search_and_ensemble_plates(document, figures)
    add_results(document)
    add_result_plates(document, figures)
    add_discussion(document)
    add_references_and_appendix(document)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    document.save(output_path)


def normalise_with_word(path: Path) -> None:
    escaped = str(path).replace("'", "''")
    script = f"""
$ErrorActionPreference = 'Stop'
$word = New-Object -ComObject Word.Application
$word.Visible = $false
try {{
    $document = $word.Documents.Open('{escaped}')
    $document.Fields.Update() | Out-Null
    $document.Repaginate()
    $document.Save()
    $document.Close()
}} finally {{
    $word.Quit()
}}
"""
    subprocess.run(["powershell", "-NoProfile", "-Command", script], check=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--no-word-normalise", action="store_true")
    args = parser.parse_args()
    output = args.output.resolve()
    build_report(output)
    if not args.no_word_normalise:
        normalise_with_word(output)
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
